//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ideaware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_factura
    {
        public int facturas_id { get; set; }
        public int productos_id { get; set; }
        public int cantidad { get; set; }
        public double valor_unitario { get; set; }
        public int id { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
